### ISSUE TITLE
Question: Protocols for contribution?

### ISSUE THREAD

**Issue by Benjamin-Piper** [MeetMartin/lambda#5]
Hi,

I'm new to making contributions to other repos, but I have a couple functions that I think would fit nicely here.

Do you have any protocols for pull requests and suggestions?

**Comment by MeetMartin** [comment]
Hi Benjamin,

If you feel confident about your code you can simply use a standard process for pull requests https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests. I will get a notification and review your code or start a discussion under it.

If you want to start with suggestions and discuss what you feel is missing first, just use the github issues as you have done now.

For me, it's important to maintain certain purity from a functional code perspective.

Otherwise, the documentation for the website gets generated automatically from the code documentation. This is why the in-code documentation tends to be quite large.

I am happy to work together to make this all click :)

**Comment by Benjamin-Piper** [comment]
Thanks, I'll open up a pull request.
