### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ztyree42** [MeetMartin/lambda#7]
Your doc site at https://www.7urtle.com/javascript-functional-programming-basics

has a snippet on partial application of curried functions:

![Screenshot from 2021-07-21 20-11-39](https://user-images.githubusercontent.com/17054909/126585174-6d8dcb72-9e43-4b3f-b324-41be2d8b6a69.png)

on line 6 `const add5PointFree = add(a);` should be `const add5PointFree = add(5);`

I can do the PR if you like but I don't know where your repo for the docs are.

**Comment by MeetMartin** [comment]
Thank you for reporting. I fixed the issue on lines 5 and 6.
The website itself is managed in a private repo. Code documentation on https://www.7urtle.com/documentation-7urtle-lambda is built through a script from the actual in-code documentation of each function
The learn pages, where this issue was, are part of the website and therefore private.
Let me know if you find any more issues :)
