### ISSUE TITLE
Maybe returns Nothing for DOM node

### ISSUE THREAD

**Issue by sbakht** [MeetMartin/lambda#8]
I copied the example from the tutorial and noticed that the Maybe is Nothing for a dom node, Either works properly

```javascript
console.log(L.Maybe.of(document.getElementById('app')).value) // null
console.log(L.Either.of(document.getElementById('app')).value) // dom node
````

See the following pen: https://codepen.io/iwanthotdog/pen/gOxeaQG

**Comment by MeetMartin** [comment]
@sbakht you are right. It is because HTML element is evaluated as empty. I will add a check for HTML and SVG elements to fix that. Thank you for the report.
Also unlike Maybe, Either doesn't have any internal check (unless you use Either.try for a function). Either is usually used as a Success or Failure output of your function.

**Comment by MeetMartin** [comment]
@sbakht this has now been fixed and your code pan works as expected
isElement and isNotElement were added to the library https://www.7urtle.com/documentation-7urtle-lambda#lambda-isElement
These affect isEmpty, which affect isNothing, which affect Maybe monad
If you find any more issues or if you have any questions, please reach out again.
